work_dir: './work_dir/prediction/input_pva'
weights: ./work_dir/prediction/input_pva/fusion_1/adam_1e-4/noseperate/iter22500_model.pt
data_dir: './data/h3.6m/dataset'

actions: 'all'
subtrain: [1,6,7,8,9,11]
subtest: [5]
batch_size: 64
source_seq_len: 50
target_seq_len: 10

model: net.model.Model
model_args:
  n_in_enc: 3
  n_hid_enc: 256
  n_in_dec: 9
  n_hid_dec: 256
  fusion_layer: 1
  seperate: False
  graph_args_j:
    layout: 'h36m'
    strategy: 'spatial'
  graph_args_p:
    layout: 'h36m'
    strategy: 'spatial'
edge_importance_weighting: True
 
phase: test
device: [3]
use_gpu: True
iter_num: 50000
weight_decay: 0.0001
optimizer: 'Adam'
step: [20000, 40000]
base_lr: 0.0001

lamda_part: 1.0
fusion_layer_dir: fusion_1
learning_rate_dir: adam_1e-4
note: noseperate